[2024-04-15T13:33:40.504+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T13:33:40.525+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T13:33:40.527+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-15T13:33:40.554+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2024-04-14 00:00:00+00:00
[2024-04-15T13:33:40.567+0000] {standard_task_runner.py:60} INFO - Started process 74 to run task
[2024-04-15T13:33:40.583+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'eksplorasii_dag', 'create_fruits_table', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi.py', '--cfg-path', '/tmp/tmptchupk1r']
[2024-04-15T13:33:40.599+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask create_fruits_table
[2024-04-15T13:33:40.743+0000] {task_command.py:423} INFO - Running <TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2024-04-14T00:00:00+00:00 [running]> on host 962ac5502d16
[2024-04-15T13:33:40.951+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='eksplorasii_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T13:33:40.955+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );

        -- Perbaikan: Menambahkan sequence fruits_id_seq
        CREATE SEQUENCE IF NOT EXISTS fruits_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;
    
[2024-04-15T13:33:40.974+0000] {base.py:83} INFO - Using connection ID 'eksplorasi' for task execution.
[2024-04-15T13:33:40.990+0000] {base.py:83} INFO - Using connection ID 'eksplorasi' for task execution.
[2024-04-15T13:33:40.993+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-04-15T13:33:41.011+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=eksplorasii_dag, task_id=create_fruits_table, execution_date=20240414T000000, start_date=20240415T133340, end_date=20240415T133341
[2024-04-15T13:33:41.048+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 229 for task create_fruits_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 74)
[2024-04-15T13:33:41.082+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T13:33:41.189+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-15T13:33:41.256+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
