[2024-04-13T18:32:28.372+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:32:25.898035+00:00 [queued]>
[2024-04-13T18:32:28.389+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:32:25.898035+00:00 [queued]>
[2024-04-13T18:32:28.391+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-13T18:32:28.421+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_fruits_table> on 2024-04-13 18:32:25.898035+00:00
[2024-04-13T18:32:28.431+0000] {standard_task_runner.py:60} INFO - Started process 305 to run task
[2024-04-13T18:32:28.438+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fruits_data_pipeline', 'create_fruits_table', 'manual__2024-04-13T18:32:25.898035+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi.py', '--cfg-path', '/tmp/tmpdl87cjo9']
[2024-04-13T18:32:28.444+0000] {standard_task_runner.py:88} INFO - Job 165: Subtask create_fruits_table
[2024-04-13T18:32:28.521+0000] {task_command.py:423} INFO - Running <TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:32:25.898035+00:00 [running]> on host b46e24c16c09
[2024-04-13T18:32:28.643+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='fruits_data_pipeline' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T18:32:25.898035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T18:32:25.898035+00:00'
[2024-04-13T18:32:28.648+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/eksplorasi.py", line 26, in create_fruits_table
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-04-13T18:32:28.670+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=fruits_data_pipeline, task_id=create_fruits_table, execution_date=20240413T183225, start_date=20240413T183228, end_date=20240413T183228
[2024-04-13T18:32:28.711+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 165 for task create_fruits_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 305)
[2024-04-13T18:32:28.774+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T18:32:28.794+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-04-13T18:32:28.837+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
